// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: d1S8dWKKr4PVKg3azHqMAd
// Component: KY3VR_cw940f
import * as React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import {
  PlasmicImg as PlasmicImg__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  generateStateOnChangeProp,
  generateStateValueProp,
  get as $stateGet,
  set as $stateSet,
  useDollarState
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { usePlasmicDataOp } from "@plasmicapp/react-web/lib/data-sources";
import NavBar from "../../NavBar"; // plasmic-import: KnagBLotfm8n/component
import { UploadWrapper } from "@plasmicpkgs/antd5/skinny/registerUpload";
import TextInput from "../../TextInput"; // plasmic-import: B7pg-YS7wyr5/component
import Combobox from "../../Combobox"; // plasmic-import: X52kQRY_iq9Z/component
import MenuItem from "../../MenuItem"; // plasmic-import: zcnybJ5YUZhH/component
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: d1S8dWKKr4PVKg3azHqMAd/projectcss
import sty from "./PlasmicProfileEdit.module.css"; // plasmic-import: KY3VR_cw940f/css

createPlasmicElementProxy;

export const PlasmicProfileEdit__VariantProps = new Array();

export const PlasmicProfileEdit__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicProfileEdit__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  let [$queries, setDollarQueries] = React.useState({});
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "navBar.proTooltip",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "navBar.statTooltip",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "navBar.caltooltip",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "navBar.messTooltip",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "usernameEdit",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => true
      },
      {
        path: "password.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "passwordEdit",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => true
      },
      {
        path: "email.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "emailEdit",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => true
      },
      {
        path: "personalityType.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "mbti.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "upload.files",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $ctx }) => []
      },
      {
        path: "navBar.friendsTooltip",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "ok",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: $queries,
    $refs
  });
  const new$Queries = {
    componentData: usePlasmicDataOp(() => {
      return {
        sourceId: "jPx9VXTMGhi2nPHAixuLPM",
        opId: "d3669a13-068f-4053-b073-74632e9142a7",
        userArgs: {},
        cacheKey: `plasmic.$.d3669a13-068f-4053-b073-74632e9142a7.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    })
  };
  if (Object.keys(new$Queries).some(k => new$Queries[k] !== $queries[k])) {
    setDollarQueries(new$Queries);
    $queries = new$Queries;
  }
  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root
          )}
        >
          <NavBar
            data-plasmic-name={"navBar"}
            data-plasmic-override={overrides.navBar}
            caltooltip={generateStateValueProp($state, [
              "navBar",
              "caltooltip"
            ])}
            className={classNames("__wab_instance", sty.navBar)}
            friendsTooltip={generateStateValueProp($state, [
              "navBar",
              "friendsTooltip"
            ])}
            messTooltip={generateStateValueProp($state, [
              "navBar",
              "messTooltip"
            ])}
            onCaltooltipChange={async (...eventArgs) => {
              generateStateOnChangeProp($state, ["navBar", "caltooltip"]).apply(
                null,
                eventArgs
              );
              if (
                eventArgs.length > 1 &&
                eventArgs[1] &&
                eventArgs[1]._plasmic_state_init_
              ) {
                return;
              }
            }}
            onFriendsTooltipChange={async (...eventArgs) => {
              generateStateOnChangeProp($state, [
                "navBar",
                "friendsTooltip"
              ]).apply(null, eventArgs);
              if (
                eventArgs.length > 1 &&
                eventArgs[1] &&
                eventArgs[1]._plasmic_state_init_
              ) {
                return;
              }
            }}
            onMessTooltipChange={async (...eventArgs) => {
              generateStateOnChangeProp($state, [
                "navBar",
                "messTooltip"
              ]).apply(null, eventArgs);
              if (
                eventArgs.length > 1 &&
                eventArgs[1] &&
                eventArgs[1]._plasmic_state_init_
              ) {
                return;
              }
            }}
            onProTooltipChange={async (...eventArgs) => {
              generateStateOnChangeProp($state, ["navBar", "proTooltip"]).apply(
                null,
                eventArgs
              );
              if (
                eventArgs.length > 1 &&
                eventArgs[1] &&
                eventArgs[1]._plasmic_state_init_
              ) {
                return;
              }
            }}
            onStatTooltipChange={async (...eventArgs) => {
              generateStateOnChangeProp($state, [
                "navBar",
                "statTooltip"
              ]).apply(null, eventArgs);
              if (
                eventArgs.length > 1 &&
                eventArgs[1] &&
                eventArgs[1]._plasmic_state_init_
              ) {
                return;
              }
            }}
            proTooltip={generateStateValueProp($state, [
              "navBar",
              "proTooltip"
            ])}
            statTooltip={generateStateValueProp($state, [
              "navBar",
              "statTooltip"
            ])}
          />

          <div className={classNames(projectcss.all, sty.freeBox__zq8Sl)}>
            <div className={classNames(projectcss.all, sty.freeBox___1RiE)}>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__uL5Ib)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/friendo/images/icons8ProfilePicture96Png.png",
                  fullWidth: 96,
                  fullHeight: 96,
                  aspectRatio: undefined
                }}
              />

              <UploadWrapper
                data-plasmic-name={"upload"}
                data-plasmic-override={overrides.upload}
                accept={""}
                className={classNames("__wab_instance", sty.upload)}
                files={generateStateValueProp($state, ["upload", "files"])}
                onFilesChange={async (...eventArgs) => {
                  generateStateOnChangeProp($state, ["upload", "files"]).apply(
                    null,
                    eventArgs
                  );
                }}
                showUploadList={true}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__tfedi)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/friendo/images/icons8Upload24Png.png",
                    fullWidth: 24,
                    fullHeight: 24,
                    aspectRatio: undefined
                  }}
                />
              </UploadWrapper>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__sNsix)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__cokFd
                )}
              >
                {"Username:"}
              </div>
              {(() => {
                try {
                  return $state.usernameEdit;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return true;
                  }
                  throw e;
                }
              })() ? (
                <div className={classNames(projectcss.all, sty.freeBox__nyfjk)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zGyMc
                    )}
                  >
                    <React.Fragment>
                      {(() => {
                        try {
                          return $queries.componentData.data.find(
                            user => user.jwt_token === $ctx.query.username
                          ).username;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return " ";
                          }
                          throw e;
                        }
                      })()}
                    </React.Fragment>
                  </div>
                </div>
              ) : null}
            </div>
            <div className={classNames(projectcss.all, sty.freeBox___9Fq2X)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__vp2A0
                )}
              >
                {"Password:"}
              </div>
              {(() => {
                try {
                  return !$state.passwordEdit;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return true;
                  }
                  throw e;
                }
              })() ? (
                <div className={classNames(projectcss.all, sty.freeBox__mtQxW)}>
                  <TextInput
                    data-plasmic-name={"password"}
                    data-plasmic-override={overrides.password}
                    className={classNames("__wab_instance", sty.password)}
                    defaultValue={(() => {
                      try {
                        return $queries.componentData.data.find(
                          user => user.jwt_token === $ctx.query.username
                        ).password_hash;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return undefined;
                        }
                        throw e;
                      }
                    })()}
                    onChange={async (...eventArgs) => {
                      generateStateOnChangeProp($state, [
                        "password",
                        "value"
                      ]).apply(null, eventArgs);
                      if (
                        eventArgs.length > 1 &&
                        eventArgs[1] &&
                        eventArgs[1]._plasmic_state_init_
                      ) {
                        return;
                      }
                    }}
                  />
                </div>
              ) : null}
              {(() => {
                try {
                  return $state.passwordEdit;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return true;
                  }
                  throw e;
                }
              })() ? (
                <div className={classNames(projectcss.all, sty.freeBox__cb9QW)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__aU4
                    )}
                  >
                    <React.Fragment>
                      {(() => {
                        try {
                          return $queries.componentData.data.find(
                            user => user.jwt_token === $ctx.query.username
                          ).password_hash;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return " ";
                          }
                          throw e;
                        }
                      })()}
                    </React.Fragment>
                  </div>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___7B8Dz)}
                    displayHeight={"20px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"20px"}
                    loading={"lazy"}
                    onClick={async event => {
                      const $steps = {};
                      $steps["updatePasswordEdit"] = true
                        ? (() => {
                            const actionArgs = {
                              variable: {
                                objRoot: $state,
                                variablePath: ["passwordEdit"]
                              },
                              operation: 0
                            };
                            return (({
                              variable,
                              value,
                              startIndex,
                              deleteCount
                            }) => {
                              if (!variable) {
                                return;
                              }
                              const { objRoot, variablePath } = variable;
                              $stateSet(objRoot, variablePath, value);
                              return value;
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["updatePasswordEdit"] != null &&
                        typeof $steps["updatePasswordEdit"] === "object" &&
                        typeof $steps["updatePasswordEdit"].then === "function"
                      ) {
                        $steps["updatePasswordEdit"] = await $steps[
                          "updatePasswordEdit"
                        ];
                      }
                    }}
                    src={{
                      src: "/plasmic/friendo/images/icons8Edit24Png.png",
                      fullWidth: 24,
                      fullHeight: 24,
                      aspectRatio: undefined
                    }}
                  />
                </div>
              ) : null}
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__hvHvu)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__h5GxO
                )}
              >
                {"Email adress:"}
              </div>
              {(() => {
                try {
                  return !$state.emailEdit;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return true;
                  }
                  throw e;
                }
              })() ? (
                <div className={classNames(projectcss.all, sty.freeBox__ropOd)}>
                  <TextInput
                    data-plasmic-name={"email"}
                    data-plasmic-override={overrides.email}
                    className={classNames("__wab_instance", sty.email)}
                    defaultValue={(() => {
                      try {
                        return $queries.componentData.data.find(
                          user => user.jwt_token === $ctx.query.username
                        ).email;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return undefined;
                        }
                        throw e;
                      }
                    })()}
                    onChange={async (...eventArgs) => {
                      generateStateOnChangeProp($state, [
                        "email",
                        "value"
                      ]).apply(null, eventArgs);
                      if (
                        eventArgs.length > 1 &&
                        eventArgs[1] &&
                        eventArgs[1]._plasmic_state_init_
                      ) {
                        return;
                      }
                    }}
                  />
                </div>
              ) : null}
              {(() => {
                try {
                  return $state.emailEdit;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return true;
                  }
                  throw e;
                }
              })() ? (
                <div className={classNames(projectcss.all, sty.freeBox__aE3R5)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__vwQdj
                    )}
                  >
                    <React.Fragment>
                      {(() => {
                        try {
                          return $queries.componentData.data.find(
                            user => user.jwt_token === $ctx.query.username
                          ).email;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return " ";
                          }
                          throw e;
                        }
                      })()}
                    </React.Fragment>
                  </div>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__wWsip)}
                    displayHeight={"20px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"20px"}
                    loading={"lazy"}
                    onClick={async event => {
                      const $steps = {};
                      $steps["updateEmailEdit"] = true
                        ? (() => {
                            const actionArgs = {
                              variable: {
                                objRoot: $state,
                                variablePath: ["emailEdit"]
                              },
                              operation: 4
                            };
                            return (({
                              variable,
                              value,
                              startIndex,
                              deleteCount
                            }) => {
                              if (!variable) {
                                return;
                              }
                              const { objRoot, variablePath } = variable;
                              const oldValue = $stateGet(objRoot, variablePath);
                              $stateSet(objRoot, variablePath, !oldValue);
                              return !oldValue;
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["updateEmailEdit"] != null &&
                        typeof $steps["updateEmailEdit"] === "object" &&
                        typeof $steps["updateEmailEdit"].then === "function"
                      ) {
                        $steps["updateEmailEdit"] = await $steps[
                          "updateEmailEdit"
                        ];
                      }
                    }}
                    src={{
                      src: "/plasmic/friendo/images/icons8Edit24Png.png",
                      fullWidth: 24,
                      fullHeight: 24,
                      aspectRatio: undefined
                    }}
                  />
                </div>
              ) : null}
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__qjD6G)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__hoa7K
                )}
              >
                {"Personality type:"}
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__p6HzV)}>
                <Combobox
                  data-plasmic-name={"personalityType"}
                  data-plasmic-override={overrides.personalityType}
                  className={classNames("__wab_instance", sty.personalityType)}
                  items={
                    <React.Fragment>
                      <MenuItem label={"Introvert"} value={"Introvert"} />
                      <MenuItem label={"extrovert"} value={"Extrovert"} />
                    </React.Fragment>
                  }
                  onChange={async (...eventArgs) => {
                    generateStateOnChangeProp($state, [
                      "personalityType",
                      "value"
                    ]).apply(null, eventArgs);
                    if (
                      eventArgs.length > 1 &&
                      eventArgs[1] &&
                      eventArgs[1]._plasmic_state_init_
                    ) {
                      return;
                    }
                  }}
                  placeholder={(() => {
                    try {
                      return $queries.componentData.data.find(
                        user => user.jwt_token === $ctx.query.username
                      ).personality_type;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return undefined;
                      }
                      throw e;
                    }
                  })()}
                />
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__uu8Oy)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__s0Lb
                  )}
                >
                  {"Extrovert"}
                </div>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__yfOpC)}
                  displayHeight={"20px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"20px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/friendo/images/icons8Edit24Png.png",
                    fullWidth: 24,
                    fullHeight: 24,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__g9Doq)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__tUuci
                )}
              >
                {"MBTI Type: "}
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__vVlf2)}>
                <Combobox
                  data-plasmic-name={"mbti"}
                  data-plasmic-override={overrides.mbti}
                  className={classNames("__wab_instance", sty.mbti)}
                  description={null}
                  items={
                    <React.Fragment>
                      <MenuItem label={"INFJ"} value={"INFJ"} />
                      <MenuItem label={"INFP"} value={"INFP"} />
                      <MenuItem label={"INTJ"} value={"INTJ"} />
                      <MenuItem label={"INTP"} value={"INTP"} />
                      <MenuItem label={"ISFJ"} value={"ISFJ"} />
                      <MenuItem label={"ISFP"} value={"ISFP"} />
                      <MenuItem label={"ISTJ"} value={"ISTJ"} />
                      <MenuItem label={"ISTP"} value={"ISTP"} />
                      <MenuItem label={"ENFJ"} value={"ENFJ"} />
                      <MenuItem label={"ENFP"} value={"ENFP"} />
                      <MenuItem label={"ENTJ"} value={"ENTJ"} />
                      <MenuItem label={"ENTP"} value={"ENTP"} />
                      <MenuItem label={"ESFJ"} value={"ESFJ"} />
                      <MenuItem label={"ESFP"} value={"ESFP"} />
                      <MenuItem label={"ESTJ"} value={"ESTJ"} />
                      <MenuItem label={"ESTP"} value={"ESTP"} />
                    </React.Fragment>
                  }
                  onChange={async (...eventArgs) => {
                    generateStateOnChangeProp($state, ["mbti", "value"]).apply(
                      null,
                      eventArgs
                    );
                    if (
                      eventArgs.length > 1 &&
                      eventArgs[1] &&
                      eventArgs[1]._plasmic_state_init_
                    ) {
                      return;
                    }
                  }}
                  placeholder={(() => {
                    try {
                      return $queries.componentData.data.find(
                        user => user.jwt_token === $ctx.query.username
                      ).mbti;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return undefined;
                      }
                      throw e;
                    }
                  })()}
                />
              </div>
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__ho3AR
              )}
              onClick={async event => {
                const $steps = {};
                $steps["runCode"] = true
                  ? (() => {
                      const actionArgs = {
                        customFunction: async () => {
                          return (async () => {
                            const password = $state.password?.value || "";
                            const email =
                              $state.email?.value ||
                              $queries.componentData.data.find(
                                user => user.jwt_token === $ctx.query.username
                              ).email ||
                              "";
                            const personality_type =
                              $state.personalityType?.value || "";
                            const mbti = $state.mbti?.value || "";
                            const jwt = $ctx.query.username;
                            async function fetchData() {
                              const API_URL =
                                "http://127.0.0.1:8000/user/update";
                              const requestData = {
                                password: password,
                                email: email,
                                personality_type: personality_type,
                                mbti: mbti,
                                token: jwt
                              };
                              console.log(requestData);
                              try {
                                const response = await fetch(API_URL, {
                                  method: "PUT",
                                  headers: {
                                    "Content-Type": "application/json"
                                  },
                                  body: JSON.stringify(requestData)
                                });
                                const responseBody = await response.json();
                                if (
                                  responseBody.username ===
                                  $queries.componentData.data.find(
                                    user =>
                                      user.jwt_token === $ctx.query.username
                                  ).username
                                ) {
                                  $state.ok = true;
                                }
                              } catch (error) {
                                console.error("Error fetching API:", error);
                              }
                            }
                            return fetchData();
                          })();
                        }
                      };
                      return (({ customFunction }) => {
                        return customFunction();
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["runCode"] != null &&
                  typeof $steps["runCode"] === "object" &&
                  typeof $steps["runCode"].then === "function"
                ) {
                  $steps["runCode"] = await $steps["runCode"];
                }
              }}
            >
              {"OK"}
            </div>
            {(() => {
              try {
                return $state.ok;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return true;
                }
                throw e;
              }
            })() ? (
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___4Bcd
                )}
              >
                {"submitted, please refresh the page"}
              </div>
            ) : null}
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "navBar",
    "upload",
    "password",
    "email",
    "personalityType",
    "mbti"
  ],

  navBar: ["navBar"],
  upload: ["upload"],
  password: ["password"],
  email: ["email"],
  personalityType: ["personalityType"],
  mbti: ["mbti"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicProfileEdit__ArgProps,
          internalVariantPropNames: PlasmicProfileEdit__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicProfileEdit__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicProfileEdit";
  } else {
    func.displayName = `PlasmicProfileEdit.${nodeName}`;
  }
  return func;
}

export const PlasmicProfileEdit = Object.assign(
  // Top-level PlasmicProfileEdit renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navBar: makeNodeComponent("navBar"),
    upload: makeNodeComponent("upload"),
    password: makeNodeComponent("password"),
    email: makeNodeComponent("email"),
    personalityType: makeNodeComponent("personalityType"),
    mbti: makeNodeComponent("mbti"),
    // Metadata about props expected for PlasmicProfileEdit
    internalVariantProps: PlasmicProfileEdit__VariantProps,
    internalArgProps: PlasmicProfileEdit__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicProfileEdit;
/* prettier-ignore-end */
